<?php

namespace Free\AnamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CnopsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CnopsRepository extends EntityRepository
{
}
