<?php

namespace Free\AnamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementRepository extends EntityRepository
{
}
