<?php

namespace Free\AnamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * faculteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaculteRepository extends EntityRepository
{
}
